### ISSUE TITLE
FOSDEM 2018 Pictures

### ISSUE THREAD

**Issue by raghunayyar** [opensourcedesign/events#107]
I think we could add the photos here?

**Comment by raghunayyar** [comment]
https://imgur.com/a/DPjDU

**Comment by evalica** [comment]
I've tweeted at https://twitter.com/opensrcdesign/status/960915694299828229 
Raghu, this are wonderful photos. Thank you so much!

**Comment by evalica** [comment]
Should we also change the https://twitter.com/opensrcdesign banner? How about http://opensourcedesign.net/ banner?

**Comment by raghunayyar** [comment]
I have one more very cool photo. Feel free to tweet it from the twitter handle: https://imgur.com/a/yP7LO

**Comment by belenbarrospena** [comment]
thanks for the photos, Raghu! And thanks for the gif, Caty! It was
hilarious :D

**Comment by davelab6** [comment]
I'm unsure if there's any further actions here; should this issue be closed?

**Comment by belenbarrospena** [comment]
Yes, I think this can be closed.
