### ISSUE TITLE
Make gh-pages default, move remaining master content over, then delete?

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/events#11]
@Xaviju to make it simpler it would be good if we only use one branch, in this case gh-pages. Can you copy the remaining content of the master branch over?

cc @bnvk

**Comment by Xaviju** [comment]
Sure!

**Comment by Xaviju** [comment]
@bnvk looks like you already moved and deleted it?

**Comment by jancborchardt** [comment]
Um @bnvk you just replaced what was on master (like your image and my writeup) with what was on gh-pages. So the other way around :\

**Comment by jancborchardt** [comment]
@bnvk so do you not want the stuff which was in here: https://github.com/opensourcedesign/events/tree/64f814c702e1b098b0bd11769f419dfcfc053527/2015-03-15%20Berlin%20Open%20Source%20Design%20meetup after all? We should add it to the events repo or somewhere, no?

After that we can remove the master branch.

**Comment by bnvk** [comment]
@jancborchardt  ack, no, I didn't mean to do that. Thanks for catching it.

**Comment by simonv3** [comment]
What's the status of this?

**Comment by jancborchardt** [comment]
@bnvk is everything you need on gh-pages? Can you make sure and then remove master?

**Comment by ei8fdb** [comment]
This looks like its done?

Doing some cleaning..reopen if needed?
🏠 👷

**Comment by bnvk** [comment]
We actually no longer need to (and probably should not) be doing the `gh-pages` branch thing since Github now allows one to choose if one wants to use the `master` branch. For repos with code / app as well as a jekyll site this makes sense, but for our purposes we should just use `master` for all the repos IMHO

**Comment by jancborchardt** [comment]
@bnvk yup, agree with that as it makes stuff simpler. :) Also still I think it would help ease of organization and newcomers if we think about combining repos more. ;)
