### ISSUE TITLE
Ladies that UX event in Berlin (connecting Open Source Design)

### ISSUE THREAD

**Issue by dimitrieh** [opensourcedesign/events#113]
@jancborchardt I thought this might be interesting for you bunch over there in Berlin 😉 

I am personally engaged with their organization as a mentor and have found it to be very interesting. This might be a great chance to connect "Open Source Design" with "Ladies that UX" 😄

https://www.meetup.com/nl-NL/LTUX-Berlin/events/251205024/

**Comment by jancborchardt** [comment]
@dimitrieh yeah, that's cool! :) We need to also get the regular meetup going again.

Do you mind posting this in the forum (Events/Berlin category) at https://discourse.opensourcedesign.net 
– we only use Github for technical website stuff now. (Could move to GitLab too, once https for custom domains is as integrated as on GitHub :)

**Comment by HeikoTietze** [comment]
Have been there two years ago and it was a unexpected well-frequented event. And as usual for Wikimedia also well organized. Remember rumors that organizers didn't want to continue but that might be wrong.
But I believe it's a lot work in preparation as the volunteers not necessarily know what and where to do. So manpower granted, who has concrete ideas? (Besides this event I think those kind of simple tasks makes it easy to join a community; LibreOffice calls it easyhacks- code that more or less everyone can write.)

**Comment by dimitrieh** [comment]
> we only use Github for technical website stuff now. (Could move to GitLab too, once https for custom domains is as integrated as on GitHub :)

@jancborchardt You can push towards http://netlify.com/ with gitlab CI/CD which has automatic renewable https ;)

---

Done! https://discourse.opensourcedesign.net/t/ladies-that-ux-event-in-berlin-connecting-open-source-design/659

**Comment by jancborchardt** [comment]
@dimitrieh thanks! :) @HeikoTietze let’s continue the discussion on Discourse. :)
