### ISSUE TITLE
Render "Past Events" differently than Upcoming or Current Events

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/events#13]
On the main http://opensourcedesign.net/events/ page, I think we should show past events as a simple one line entry instead of the whole blurp as this list could get looooooong!

**Comment by jancborchardt** [comment]
Yup, totally agree. Header to separate and single line only.

**Comment by ei8fdb** [comment]
This looks like its done:

### Current OSD events page showing "future events"
![](http://i.imgur.com/FQln0zU.png)


### Current OSD events page showing "past events"
![](http://i.imgur.com/z2NALsI.png)

I'm going to close it, but reopen if necessary.
