### ISSUE TITLE
Use Jekyll metadata instead of custom defined date / time data in events

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/events#15]
As @jancborchardt @simonv3 chat here https://github.com/opensourcedesign/events/pull/14 I fully agree  and thought the same thing and am creating an issue as such!

**Comment by Xaviju** [comment]
:+1: Agree!

**Comment by ei8fdb** [comment]
This looks like its been merged. Time to close? Or no?

**Comment by bnvk** [comment]
Mmmm. I don't thinkthis is ready to be closed!

**Comment by davelab6** [comment]
I believe this should be closed, I think the post publication date is legitimately different to the event date :)
