### ISSUE TITLE
IxDA 2016 - Helsinki

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/events#21]
IxDA submissions close on September 15th. It's in Helsinki. If any of you europeans want to go and represent OSD that would be great.

Conference Site:
http://interaction16.ixda.org/

IxDA:
http://ixda.org/

Email Announcement:
http://us2.campaign-archive1.com/?u=e714c585710f24c2743e2cb29&id=c16aa91d1f&e=4e3854aa38

**Comment by elioqoshi** [comment]
Thanks for the headsup, I am going to apply tomorrow! :)

**Comment by elioqoshi** [comment]
Applied here with my "Overcoming your designer ego in an open source project" talk.
A bit of scared, the quality of the conference seems to be tremendously high :D

**Comment by ei8fdb** [comment]
I'm going to close this since it's about an event thats already happened.
