### ISSUE TITLE
Page link too long

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/events#26]
The link for an event looks like this: http://opensourcedesign.net/events/design/hack/meeting/2016/01/30/opensourcedesign-fosdem.html

At least this section with design/hack/meeting (the tags?) is way too much. Ideally even the date is not needed.

**Comment by simonv3** [comment]
This is the same for articles. What it's doing is it's putting all the categories in the URL. This isn't really what we want I think.

**Comment by gillisig** [comment]
I agree, it's unnecessary if you ask me. I guess Jekyll does this by default for some reason.

**Comment by simonv3** [comment]
I think having the date is fine, though I guess for something like events it's not necessary. The real question though, now that it's there - will it break back-linking?

**Comment by dominicrico** [comment]
In jekyll you can set the `permalink` attribute per page. So we can have the event name with dashes as link to the page. And there is also a plugin which is redirecting the old urls to the new ones.
- [Permalink Blog Post](http://joshualande.com/redirect-urls-jekyll-github/)
- [Redirect Plugin Blog Post](http://joshualande.com/redirect-urls-jekyll-github/)

**Comment by simonv3** [comment]
@dominicrico setting permalink would be a good idea. Re: plugin we can't do plugins because it's GitHub :P

**Comment by dominicrico** [comment]
@simonv3  oops, true we are not allowed to used plugins, buuuuut after asking the mighty internet I found out, github has this one pre installed :D 
[Github Pages Plugins](https://help.github.com/articles/using-jekyll-plugins-with-github-pages/)

**Comment by simonv3** [comment]
Yay!

**Comment by dominicrico** [comment]
I'm working on it right now. I will update the links for the articles as well!

**Comment by dominicrico** [comment]
@simonv3, @jancborchardt, or someone else. Please review and merge if it is ok.

**Comment by dominicrico** [comment]
Could be tested for articles with:
http://opensourcedesign.net/monthly-update/2015/07/10/this-month-in-open-source-design.html

And for events: ( must be merged first ;) )
http://opensourcedesign.net/events/design/hack/meeting/2016/12/07/libre-graphics-meeeting.html

**Comment by simonv3** [comment]
Both of those work :)

**Comment by jancborchardt** [comment]
Thanks a lot @dominicrico! :)
