### ISSUE TITLE
Libre Graphics Meeting 2016

### ISSUE THREAD

**Issue by aoloe** [opensourcedesign/events#27]
http://libregraphicsmeeting.org/2016/call-for-participation/
### Other Dimensions

The eleventh annual international Libre Graphics Meeting 2016 will take place Friday 15th until Monday 18th April 2016 in London, UK. This yearly event is an occasion for teams and individual contributors/artists involved in Libre Graphics to work together, to share experiences and to hear about new ideas. By Libre Graphics we mean Free, Libre and Open Source tools for design, illustration, photography, typography, art, graphics, page layout, publishing, 3D modelling, digital making and manufacture, cartography, animation, video, interactive media, generative graphics and visual live-coding. The Libre Graphics Meeting is not just about software, but extends to standards, file formats and actual use of these in creative work. LGM has become the place in which they can discuss their projects, coordinate their efforts and, crucially, to meet in person. Participants in the LGM include developers, designers, academics and activists from around the world, who are all passionate about Free/Libre graphics software and technology.
### State of the Libre Graphics Union

We begin each meeting with a joint session that brings together all things that have happened in our wide landscape over the last year. So, instead of slots in the schedule for general updates on each Libre Graphics software project, we invite every team present at LGM to submit two slides (maximum), with a short explanatory text that showcases the leaps forward that has been made over the past year. For first-time presenters and particular big or new topics/features in established projects, we encourage additional stand-alone submissions.

More info: http://libregraphicsmeeting.org/2016/state-of-libre-graphics-union-2016/
### Special focus: Other Dimensions

In Toronto we celebrated the first decade of LGM, reflecting on the past and considering the future. For the 2016 edition of LGM we continue speculating and will expand Libre Graphics into Other Dimensions. We are looking for presentations and workshops that explore the dimensions of space and material: 3D modelling and animation, Libre architecture, Open Source product design and other fields of digital making and manufacture. We are also seeking contributions that offer reflections on the ‘other dimensions’ of open source communities and that engage with FLOSS tools in various contexts including but not limited to teaching, learning, practice and co-production. This represents a desire to address the future sustainability of the Libre Graphics movement, through a growth of the core projects and topics that will, we hope, allow us to welcome more and more FLOSS projects and participants to our community.
### We are looking for:
- In-depth presentations of Libre Graphics code-contributions
- Showcases of excellent work made using Libre Graphics tools
- New and experimental projects in this area to meet the wider community, including those in the field of 3D design and making
- Reflections on the activities of existing open source communities in either the production of Free, Libre and Open Source tools or their use
### Available formats (times include Q&A):
- Entry for State of the Libre Graphics Union (1-2 slides)
- Presentations (20 minutes)
- Birds Of a Feather (BOF), discussion meetings or Hackathons (2 hrs or more)
- Workshops (1 or 2 hours)
- Lightning talk (7 minutes, selected at the event unconference style)
### Practical Details:

Submission deadline: 10 January 2016, content selection notification by end of January 2016. Please submit your proposal here: http://libregraphicsmeeting.org/2016/submit-proposal/

**Comment by jancborchardt** [comment]
@aoloe great! Already retweeted it from the [@opensrcdesign twitter](https://twitter.com/opensrcdesign) as well. :)

Can you also add the event to the events directory by putting it here? https://github.com/opensourcedesign/events/tree/gh-pages/_posts

**Comment by aoloe** [comment]
made a PR for the event...
questino: do you have a format for supporting the call for participation?

**Comment by xuv** [comment]
I could see that the PR for the event was accepted. But still the event did not show. 
Updated the _config file to show future events. See PR #32

**Comment by ei8fdb** [comment]
I'm going to close this since its about an event that has taken place.
