### ISSUE TITLE
OSD Meetup - Berlin Early May 2016

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/events#35]
I'm going to be in Berlin in 03-04 of May attending [csv,conf](http://csvconf.com) and possibly [Open Tech Summit](http://opentechsummit.net/) though the website is a significantly less in English than it was last year. 

Last year for OTS at that time we got some awesome people together around that time - it'd be great to do something similar and lay out a framework for other people to do this in other parts of the world as well.

@bnvk @danilapellicani @jancborchardt @jdittrich @ScintillaLuz and anyone who is around Berlin and/or interested in coming to Berlin at that time.

**Comment by jdittrich** [comment]
I'll be at OTS. There is interest in more design and usability at the OTS as far as I'm concerned; drop me a line if you are interested :)

**Comment by RichardLitt** [comment]
I _may_ be there at csv,conf with you. If so, I'll see if I can make it to the Open Tech Summit, too.

**Comment by jancborchardt** [comment]
I’ll most likely not make it to Berlin at that time. But yeah, you go for a meetup! :)

**Comment by simonv3** [comment]
@jdittrich I'd definitely be interested in talking about that. I'll shoot you an e-mail. 

@RichardLitt I'm actually thinking of doing something separate from OTS, maybe just a few hours, somewhere in a pub. 

@jancborchardt bummer. One day, we'll meet in person!

**Comment by RichardLitt** [comment]
@simonv3 I like pubs.

**Comment by ScintillaLuz** [comment]
I'll be around :)))))

btw: currently in SF, anyone I should meet??? (sorry for being off topic...)

On 28 February 2016 at 07:32, Simon notifications@github.com wrote:

> I'm going to be in Berlin in 03-04 of May attending csv,conf
> http://csvconf.com and possibly Open Tech Summit
> http://opentechsummit.net/ though the website is a significantly less
> in English than it was last year.
> 
> Last year for OTS at that time we got some awesome people together around
> that time - it'd be great to do something similar and lay out a framework
> for other people to do this in other parts of the world as well.
> 
> @bnvk https://github.com/bnvk @danilapellicani
> https://github.com/danilapellicani @jancborchardt
> https://github.com/jancborchardt @jdittrich
> https://github.com/jdittrich @ScintillaLuz
> https://github.com/ScintillaLuz and anyone who is around Berlin and/or
> interested in coming to Berlin at that time.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/opensourcedesign/events/issues/35.

## 

Valentina Montagna

+49 0151 25116127
http://shedoesscream.tumblr.com/
http://twitter.com/ScintillaLuz

**Comment by simonv3** [comment]
That's okay! Maybe start a new issue for it though? (that is what this repo is for!) A new issue with a proper header will probably attract a couple more people, whereas here they just see the Berlin meetup title and might dismiss it! Also, easier to tweet :)

**Comment by elioqoshi** [comment]
I am 90% sure I will be at OTS so meet you there guys! :)

**Comment by danilapellicani** [comment]
I should be in Berlin at that time :)

Danila Pellicani
D https://www.linkedin.com/in/danilapellicanio
https://www.linkedin.com/in/danilapellicani / Make
http://www.danilapellicani.it/ / Say https://twitter.com/danilapellicani

**Comment by jdittrich** [comment]
:+1: 
btw., if anybody has an idea for a useful workshop for Open Source Designers, drop me a line. I want to do one on paper-prototyping but may add another one (User Research, maybe?). Also, if anybody wants to collaborate on this, please tell me.

**Comment by ei8fdb** [comment]
I've got some time so am doing some house-cleaning.

I'm going to close this, mainly because it was for an event in May this year.
