### ISSUE TITLE
FOSDEM 2017 - Sessions Brainstorming Ideas

### ISSUE THREAD

**Issue by evalica** [opensourcedesign/events#45]
We should use this issue to brainstorm on sessions for the Open Source Design room. 
In order for a talk to be accepted it will still need to follow the standard process in pentabarf, but here we can gather ideas in order to not forget about them.

For room track organization see #41

**Comment by evalica** [comment]
Idea from @belenbarrospena and realitygaps (with qtpass) on IRC

> publicise the "success" stories from projects that posted design jobs and got a designer involved

This could be done as a short summary before the final session, where we have developers present their projects.

**Comment by victoria-bondarchuk** [comment]
Hi all, 

"Success stories" idea sounds awesome, as it would set a great example not only for engineers, but for designers who are looking for opportunities to be involved! 

I was thinking to submit a talk with review of existing academic research on usability and open source culture.

I want to bring up the discussion of suggested methods for usability specialists on how to engage with and contribute to FLOSS projects, with a focus on understanding open source culture, the project in question and active collaboration with the developers. 

Here is [a list of papers on usability in FOSS](https://github.com/victoria-bondarchuk/List-of-Academic-Research-on-Usability-in-FOSS) I used for a similar talk at FOSSASIA'16 

What do you guys think, will that be interesting for FOSDEM audience? 
I would appreciate any feedback as it will be my first time to Brussels ;)

**Comment by evalica** [comment]
Hi @victoria-bondarchuk . Your talk idea sounds really good. I would be interested to have a summary of that research and your findings.

I worked only for one FLOSS project, so all this comparison between corporate vs. open  or multiple FLOSS projects between them sounds interesting to me :) Since the projects usually are very diverse it's kind of hard to draw some universal conclusions, but summaries and examples tell their own story.

The questions part of the talk is usually interesting to see what other contributors experienced.
So good luck with your presentation :)

**Comment by belenbarrospena** [comment]
@victoria-bondarchuk I agree with @evalica. The talk sounds great. 

Also, thanks for putting that list of papers together!

**Comment by elioqoshi** [comment]
By the time FOSDEM starts, we at Mozilla have introduced our new logo and brand identity which was done in an open way here:
https://blog.mozilla.org/opendesign
and on GitHub as well: https://github.com/mozilla/opendesign

I'd be happy to give a talk about the new identity and how we proceeded with it

**Comment by andreasn** [comment]
I gave a talk at GUADEC this year how I used interviews as part of the process to create the design for public transportation support in GNOME Maps. I'm up for giving a variation of that talk at FOSDEM.

I would love to see the talk suggested by @victoria-bondarchuk

**Comment by belenbarrospena** [comment]
@andreasn you should really submit a proposal for that. It will be great to have someone from Gnome speaking at last :)

There was also this talk at Paris-Web 

https://www.paris-web.fr/2016/conferences/open-design.php

Maybe we can convince the speaker to drop by FOSDEM, since she might be based in Paris and should be an easy trip. I missed the talk, but the feedback I saw about it was good.

**Comment by Xaviju** [comment]
I'd love to hear someone behind a OS design team. Like the Fedora design team, Ubuntu, or elementary OS. It could also be the blender or Gimp design team. I'd like to know their workflow, how they integrate their work with the dev team...etc.
We could ask [Mairin Duffy](https://github.com/mairin) from Fedora if she can recommend someone to come to talk (she is based in Boston). I've heard some of their open design meetings and sound very interesting.

**Comment by belenbarrospena** [comment]
@xaviju I agree. I'd say go ahead and get in touch with Mairin. The Ubuntu
design team is based in London, and I think I saw someone from that team in
the #opensourcedesign channel at some point. I'll have a look

**Comment by andreasn** [comment]
@allanday who's heavily involved in the GNOME design team could also be interested in giving a talk. He's based in the UK, but i have no idea if he's planning on travelling to FOSDEM or not.

**Comment by Xaviju** [comment]
@andreasn @allanday GNOME is great! Lets see if he'd like to come. Otherwise i'll get in touch with other design teams.
Thanks @belenbarrospena, i'd love to hear about the work of the UX/UI team in Ubuntu Touch. I'd be happy to get in touch with them if you think its interesting.

**Comment by belenbarrospena** [comment]
@Xaviju sounds good to me :)

**Comment by ei8fdb** [comment]
AFAIK the elementary design team are all in the US?

Lets contact their (Fedora, Ubuntu and elementary OS) mailing lists and suggest they come.

I’m afraid I don’t know anyone so it’ll be “shoot and hope” :)

**Comment by ei8fdb** [comment]
I contacted him last year via the GNOME list and he knew about OSD (he might even be on here).

**Comment by ei8fdb** [comment]
If this is the talk at Paris Web (sorry don’t have Internet access at the moment), then I’ve already contacted the speaker

She was at FOSDEM last year and said that she really enjoyed it.

I’ve asked her if she would submit this talk to FOSDEM. She also chaired a discussion at Paris Web, which I didn’t fully understand as it was in French, but brought up lots of discussion on issues with design and open source.

Fingers crossed!

**Comment by belenbarrospena** [comment]
@ei8fdb yes, I was referring to the talk at Paris Web. Great you already got in touch with her, and great that she was there last year. Hopefully she'll come back :)

**Comment by evalica** [comment]
Closing since submission period is over. Thanks for your participation.
