### ISSUE TITLE
FOSSASIA 2017 – Open Source Design Track Planning

### ISSUE THREAD

**Issue by victoria-bondarchuk** [opensourcedesign/events#48]
**Hello everyone,** 

The biggest open source conference in Asia - [FOSSASIA](http://2017.fossasia.org/) (think FOSSDEM of Asia) is looking to attract more design talks for the next year event. 

FOSSASIA was established in 2009. Previous events took place in Cambodia and Vietnam, Singapore. In 2017 the event will take place from **March 17th – 19th** at the Science Centre Singapore.

Last event brought together more than a 1000 participants and about 200 speakers from 32 different countries.  That’s a truly global and a fantastic place to meet all kind of FOSS projects and people.  
Last year @jancborchardt and me each presented there and we even had an [Open Source Design booth](https://twitter.com/seoul_victoria/status/711073038901452800), which was a great success )) 

This year we plan to step up as hosts of Open Source Design Track there. Right now it's a planning stage and we want to reach out to potential speakers. 
Official [CFP is open already](http://blog.fossasia.org/fossasia-summit-2017-singapore-call-for-speakers/)  and deadline is December 20th, 2016.  (before FOSSDEM) 

Please, post here if you would be interested to be co-organizer of design track or a speaker this year. If you know any people who might be in that region or interested coming, please refer them to this issue. 

We will keep it posted here on the progress.  As usually any help and advices are very welcome. 

You can learn more about FOSSASIA [here ](http://fossasia.org/) or at the official [blog](http://blog.fossasia.org/) and find here some [pictures](https://www.flickr.com/photos/fossasia/page2) from last year.

**Comment by simonv3** [comment]
I am interested in helping organize this, even if I can't guarantee I'll be in the area.

**Comment by elioqoshi** [comment]
I am interested as well to help here and can also be a speaker/workshop host, talking about Open Source Design at Mozilla and/or Tor. Mozilla will probably be able to sponsor me.

**Comment by victoria-bondarchuk** [comment]
@simonv3  This is great!  Any advices how to promote this event would be very much appreciated. 

@elioqoshi Awesome! Mozilla sponsored FOSSASIA in 2015 and every year there is big Mozilla community, but I don't think there was a design talk yet. Would be great to have you speaking on design in  Mozilla and Tor! 
Host application is open already. [Track Hosts and Volunteer Registration to FOSSASIA 2017 ](http://2017.fossasia.org/volunteers/)
There is a preliminary [list of tracks](http://blog.fossasia.org/fossasia-summit-2017-singapore-call-for-speakers/), current name for the track is "Design, Art & Culture". 
Probably we can rename it based on the submitted talks' topics.

**Comment by jancborchardt** [comment]
Awesome, this is already very good! :) We should get some more designers of the Asian & Oceanic region involved. :)

cc @johnonolan @raghunayyar @rdbartlett @brampitoyo @chuaccheng @chuganzy @daminisatya @ericsonluciano @junezhang @juslee @lauweijie @pathumego will you be at FOSSASIA 2017? Would be cool if you’re up for joining the Open Source Design track and maybe giving a talk :)

**Comment by lauweijie** [comment]
@jancborchardt I live in Singapore -- would love to be there!

**Comment by raghunayyar** [comment]
I am in Stockholm now, too far, too expensive. :P

**Comment by elioqoshi** [comment]
Anyone who wants to facilitate this? I can probably help as well

**Comment by pathumego** [comment]
@victoria-bondarchuk I was planning on going to FOSSASIA anyway! I can help out with organising and talk about something relating to libre fonts, libre font tools and font projects.

**Comment by jancborchardt** [comment]
Good stuff @pathumego, would be great if you can help with organizing and giving a talk! The CfP is open at http://blog.fossasia.org/fossasia-summit-2017-singapore-call-for-speakers/

@elioqoshi sure, if you’re there anyway any help is appreciated. :) @victoria-bondarchuk and me are the track co-organizers.

**Comment by pathumego** [comment]
@jancborchardt Sure thing, Im looking forward to it. I will sign up on the volunteer form.

**Comment by victoria-bondarchuk** [comment]
Hello everyone, 

FOSSASIA CFP deadline is tomorrow on 20th of December. 
Please submit your talks here: http://2017.fossasia.org/speaker-registration/

Here are some[ pictures](https://www.flickr.com/photos/comprock/albums/72157665859400502) from last year for inspiration.

**Comment by elioqoshi** [comment]
I applied as well

**Comment by pathumego** [comment]
@victoria-bondarchuk @jancborchardt I posted for a session on Libre Fonts and my colleague @lpsandaruwan is also posted a talk. We registered as volunteers too :) But I wont be able to help out in pre-conference planning.

**Comment by victoria-bondarchuk** [comment]
@elioqoshi  @pathumego  @lpsandaruwan  very exciting! Hope to meet you all in Singapore!

**Comment by victoria-bondarchuk** [comment]
Hey everyone,
 
The submission deadline is postponed until 20 of Jan. 

Unfortunately FOSSASIA, as a very young organization, do not have the resources to provide travel funding directly. But you can request invitations, supporting documents that might help you to obtain funding from your organizations, companies or elsewhere. You can find the answers for those questions here http://speakers.fossasia.org/faq

**Comment by linchocolatte** [comment]
Hello! I have a design project regarding open-source design I would like to propose, it was part of my final year degree project, where/who can I talk to? Hope this is not too late :O If I want to volunteer for the event, where can I know more about FOSSASIA? Thanks in advance!!!

**Comment by jancborchardt** [comment]
cc @victoria-bondarchuk on your question @linchocolatte :) She coordinates the Open Source Design track at FOSSASIA.

**Comment by elioqoshi** [comment]
I think I will need to skip FOSSASIA this year. I need to take a break from international trips and wrap up my bachelor studies ;/
Sorry about that, see you at the next occassion!

**Comment by victoria-bondarchuk** [comment]
Hello @linchocolatte, are you interested to give a talk? Even though submission deadline is over, link is still open and you can give it a try:  2017.fossasia.org/speaker-registration

Track Hosts and Volunteer Registration to FOSSASIA 2017 
http://2017.fossasia.org/volunteers

About FOSSASIA:
http://2017.fossasia.org/
http://blog.fossasia.org

**Comment by victoria-bondarchuk** [comment]
@elioqoshi Sure, may be next year, hopefully FOSSASIA will be even better by 2018. See you at FOSDEM!

**Comment by linchocolatte** [comment]
@victoria-bondarchuk omg I'm not sure if I am qualified enough to give a talk D: Maybe we can discuss more first to see if my project suits the event? It is a design project related to open-source design! (:

**Comment by victoria-bondarchuk** [comment]
@linchocolatte OSD community and FOSSASIA are definitely the places where you should share your work related to open design design ;)

**Comment by linchocolatte** [comment]
@victoria-bondarchuk Thanks Victoria! (: I've submitted a proposal via the link, waiting for any responses/replies!

**Comment by evalica** [comment]
The event has passed. Closing the issue. Thanks @victoria-bondarchuk for organizing it!

**Comment by jancborchardt** [comment]
Awesome work @victoria-bondarchuk! :tada:  :)

**Comment by jancborchardt** [comment]
@victoria-bondarchuk @evalica is there any documentation of the track by the way? Any link to the program we can add to the event in the archive? :)

**Comment by jancborchardt** [comment]
Ah the best link I found was http://2017.fossasia.org/tracks.html#2017-03-19-Design,_Art,_Community :)

**Comment by victoria-bondarchuk** [comment]
@jancborchardt there is also video from the conference: 
1. [Expectations from Open Source Designers  by @evalica - FOSSASIA 2017
](https://youtu.be/3M9ptBxFyP4)
2. [ Usability testing based on user's mood by June Zhang (Beijing Redhat)](https://youtu.be/7bAmElZKzoM)
3. [Connecting design, culture, art, and technology across the archipelago](https://www.youtube.com/watch?v=IJE4I467JCw)

others talks are also on youtube, however not everything was recorded but we hope next time we will get better.

**Comment by jancborchardt** [comment]
@victoria-bondarchuk awesome! Want to write a quick post about it with the links so we can publish it on the articles page? :)

cc @evalica @simonv3

**Comment by victoria-bondarchuk** [comment]
@jancborchardt  Yes, I was planing. Let me work on it and share a draft in a week.

**Comment by jancborchardt** [comment]
@victoria-bondarchuk cool! :)
