### ISSUE TITLE
Notes from monthly Open Source Design call

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/events#49]
Our monthly Open Source Design call notes will go here! :)
If anything is missing, just edit the post. We will have one comment per meeting to keep it readable.

# Meeting 1 (October 25th 2016)

With @simonv3 @belenbarrospena @jdittrich & @jancborchardt
- **We’ll have a monthly Open Source Design call every first Tuesday of the month** at https://talky.io/opensourcedesign (@simonv3 will create an event) next one is December 6, 19:00 Berlin time.
- **We’ll set up Open Source Design at Open Collective and Bountysource** after the funding discussion at https://github.com/opensourcedesign/funding/issues/4 (@jancborchardt will do it). Bountysource is for individual issues and Open Collective could be for general expenses like stickers, domain, etc. – _not_ for covering travel costs of individuals.
- @jdittrich mentioned https://www.draw.io is now open source and could be valuable for open source design processes. Let him know your experience with it! (@jancborchardt also mentioned https://www.uxbox.io/ by the @kaleidos folks which seems in development)
- **Everyone: Hand in talks & help organizing our Open Source Design rooms** at FOSDEM Brussels and FOSSASIA Singapore! :) FOSDEM https://github.com/opensourcedesign/events/issues/45 & FOSSASIA https://github.com/opensourcedesign/events/issues/48

(Retweet at https://twitter.com/opensrcdesign/status/790976386982932481)

# Next Meetings
* [Meeting 2 (Dec 6th 2016)](https://github.com/opensourcedesign/events/issues/49#issuecomment-263360799)
* [Meeting 3 (Jan 10th 2017)](https://github.com/opensourcedesign/events/issues/49#issuecomment-266360762) - [Notes](https://github.com/opensourcedesign/events/issues/49#issuecomment-271666446)
* [Meeting 4 (Feb 14th 2017)](https://github.com/opensourcedesign/events/issues/49#issuecomment-279762039)
* [Meeting 5 (Mar 7th 2017)](https://github.com/opensourcedesign/events/issues/49#issuecomment-283646202)
* ~~[Meeting 6 (Apr 4th 2017)](https://github.com/opensourcedesign/events/issues/49#issuecomment-284827673)~~
* [Meeting 7 (May 2th 2017)](https://github.com/opensourcedesign/events/issues/49#issuecomment-298700689)
* [more... (our calendar)](https://cloud.nextcloud.com/index.php/apps/calendar/p/MIFAFLFJADIVX63I/Open-Source-Design)

**Comment by jancborchardt** [comment]
This thread will have a monthly update on what we do so it’s apt to notify all of @opensourcedesign/people. :)

**Comment by simonv3** [comment]
Note: I edited your notes to say Tuesday, they said Thursday :)

**Comment by victoria-bondarchuk** [comment]
Thank you for sharing! I wish I could join but not while i'm in Korean timezone.

**Comment by Xaviju** [comment]
I can confirm [uxbox](https://github.com/uxbox) is in development (I saw a demo yesterday). Current developers are @elhombretecla and @niwinz

**Comment by evalica** [comment]
@jancborchardt Thank you so much for gathering notes from the meeting since I was unable to participate! For the future maybe we could use Google Hangouts and maybe also record the meetings (just an idea)?

**Comment by simonv3** [comment]
FWIW I'm for that but there was pushback from others because it wasn't open - it requires having a google account, and also sharing that google account with other people in the call.

**Comment by mrphs** [comment]
There's always https://meet.jit.si we could use as an alternative.

**Comment by eighthave** [comment]
I use https://meet.jit.si a couple times a week for calls, works great.
no log-ins needed, works on Firefox and Chrome on all platforms,
including mobile.

**Comment by ei8fdb** [comment]
Can we get a notification of this meeting? I had no idea it happened until I read the notes here.

**Comment by simonv3** [comment]
@ei8fdb Yeah! Here's [an ICS file](https://oasis.sandstorm.io/shared/_cKKuCMHjF1j7N-wXar3LjSF-L_g8s-hMJ5EGKOckjY) you can add to whatever calendar you use.

**Comment by simonv3** [comment]
## Meeting 2 (December 6th 2016))
Meeting: https://talky.io/opensourcedesign

### Agenda

1. Talk to Wikimedia folks @jdittrich. 
1.  FOSDEM [#41](https://github.com/opensourcedesign/events/issues/41) stuff @evalica. 
    1.  Proposals: FOSDEM Talks [Spreadsheet](https://docs.google.com/spreadsheets/d/1-9hdoukWJgvdn_YPxGS3xMBayVTTJP29o1dGFGnMLx4/edit)
      -- Discuss about the default proposals + Decide on the responsible people + Add them to Penta
      -- Vote + decide on the final sessions (14-16) and schedule
    1. Stickers [#43](https://github.com/opensourcedesign/events/issues/43): Talk about [OpenCollective](https://opencollective.com/opensourcedesign) and the stickers design/order
      -- Agree to spend money on the stickers
      -- Decide on the stickers logo (Jan got an email from the Open Source Initiative about that btw, we should talk about what to reply)
      -- See who can do it + Talk about the reimbursement process
    1. Dinner: Discuss about the Designers Dinner on Friday before FOSDEM
1. OpenCollective Interview questions available [here](https://docs.google.com/document/d/1LNrkXNKH-KBFsz9zxn-4DBFS_q25luApbPOdu7XBo7Q/edit) Deadline: 8 Dec

### Notes
Participants: evalica, ei8fdb, gillisig, jdittrich, jancborchardt, andreasn, eppfel - Felix, other?
Next meeting: 10 January 2017, 19:00 Berlin

1. Wikimedia: We didn't had any guests from Wikimedia so we postpone it for next meeting.
1. FOSDEM
    1.  [Spreadsheet](https://docs.google.com/spreadsheets/d/1-9hdoukWJgvdn_YPxGS3xMBayVTTJP29o1dGFGnMLx4/edit#gid=905844715): 
      -- We are going to wait 2 more days to have more votes. After that we will validate the schedule. Deadline: 8 Dec
      -- We need a volunteer for the "Success Stories from our community" session. Who wants to help?
      -- Since the sessions will be held on Sunday, it was stated that it would be better to start the schedule at 10:00. What do you prefer: starting at 10? or having 14 talks instead of 12?
    1.  Stickers: 
      -- Apparently there is a problem with our logo resemblance with OSI logo. We might need to postpone the print of official stickers until we clarify the issue.
      -- still ei8fdb is willing to have a very select batch of stickers for FOSDEM with our first logo
    1.  Dinner:
      -- The general opinion is that it would be very nice to meet again at dinner. We would need to create an issue to find out the number of participants and their diet preferences.
1. OpenCollective Interview: 
      -- We started to answer the [questions](https://docs.google.com/document/d/1LNrkXNKH-KBFsz9zxn-4DBFS_q25luApbPOdu7XBo7Q/edit) but we need more help in remembering things. Any help is appreciated in making the text more nice, more funny or more realistic.
      -- Deadline is 8 Dec, so be fast

**Comment by andreasn** [comment]
Where can I find more info about next weeks call?
Date, time, place?

**Comment by evalica** [comment]
@andreasn in the issue description, or on the website at http://opensourcedesign.net/events/open-source-design-monthly-online-meeting/

**Comment by RichardLitt** [comment]
Can we add a public calendar on Google so that we can automatically see this is going to happen?

**Comment by simonv3** [comment]
I think that's a good idea. @RichardLitt do you mind setting one up? 

Are there any other "open" calendars we can do this for?

**Comment by RichardLitt** [comment]
It adds overhead; someone has to maintain the calendar. I'd rather not volunteer for that right now, as I am minimally involved in OSD at the moment. I might be able to do this after attending a call, but as I haven't been on one yet and want to see what is up, I don't think it would be the best for me to set up the calendar right now.

**Comment by mestaritonttu** [comment]
There is an instance of [Nextcloud Calendar](https://github.com/nextcloud/calendar) here: https://framagenda.org/ Provided by Framasoft.

**Comment by evalica** [comment]
We had the meeting and there were around 7 participants. I've added the [summary](https://github.com/opensourcedesign/events/issues/49#issuecomment-263360799). 
We still need help for points 2.i and 3. Deadline is 8 Dec. Help us with votes and more text for the interview.
See you next time on 10 Jan 2017.

**Comment by simonv3** [comment]
Awesome! I'm sorry I couldn't make it. My internet is a dumpster fire. I'll poke at the google docs with the answers if I get a chance :)

**Comment by Xaviju** [comment]
Thanks for the summary! I've already voted on the spreadsheet.
About the logo, I agree with @ei8fdb on having a first batch of the logo (it's a shame if we have to change it). I'd be happy to pay for it if needed.

**Comment by belenbarrospena** [comment]
Thanks @evalica for taking notes, and to all the people who attended. It is a bit too late for me while in IST.

Couple of comments on the notes:

> Since the sessions will be held on Sunday, it was stated that it would be better to start the schedule at 10:00. What do you prefer: starting at 10? or having 14 talks instead of 12?

I agree it would be better to start at 10, but with so many good submissions it would be a pity to discard another 2. So my vote goes to 14 sessions, starting at 9am, although I cringe thinking of the early morning start after all the Saturday beer ;)

> Stickers:
> -- Apparently there is a problem with our logo resemblance with OSI logo. We might need to postpone the print of official stickers until we clarify the issue.
> -- still ei8fdb is willing to have a very select batch of stickers for FOSDEM with our first logo

I am going to have to disagree with @ei8fdb on this one. I am sure nothing will happen, but I wouldn't even consider chancing it. We can totally wait until the situation with the logo is cleared up. We won't die of not having stickers ;)

> The general opinion is that it would be very nice to meet again at dinner. We would need to create an issue to find out the number of participants and their diet preferences.

Issue opened: https://github.com/opensourcedesign/events/issues/54

**Comment by jancborchardt** [comment]
Added my recollections to the history and the other points in the interview questions: https://docs.google.com/document/d/1LNrkXNKH-KBFsz9zxn-4DBFS_q25luApbPOdu7XBo7Q/edit
@bnvk would be good if you also chime in there cause you were around early on as well. :)

@belenbarrospena regarding the time, since we’re on Sunday and last year it was also a drag in the morning I would say let’s go for 10. Sure we will have less sessions, but what use is more sessions if the first ones (namely the introduction and success stories) are attended by almost no one? ;)
That’s why starting at 10 I think is a sensible move, paired with having an entry in the schedule at 9:30 called »Welcome & chatting« so people already arrive.

Regarding the logo I will cc you folks on the email from the Open Source Initiative – sorry for the late notice as I just remembered it then. We’ll keep it positive and hopefully we can keep the logo or only do minimal adjustments. @Xaviju @belenbarrospena @simonv3 @evalica etc.

**Comment by belenbarrospena** [comment]
> @belenbarrospena regarding the time, since we’re on Sunday and last year it was also a drag in the morning I would say let’s go for 10. Sure we will have less sessions, but what use is more sessions if the first ones (namely the introduction and success stories) are attended by almost no one? ;)

@jancborchardt Well, call me an optimist, I am hoping that we'll get the video working this time ;) which means the talks will be there for posterity, even if the room is not full on the day.

I just feel a bit sorry about throwing away good content, that's all. If my session makes it in, I'll happily volunteer for one of the "ghost" morning slots :D

**Comment by evalica** [comment]
## Meeting 3 (January 10th 2017) - Agenda
Meeting: https://talky.io/opensourcedesign

#### Topics
1. FOSDEM
1. [Logo](https://github.com/opensourcedesign/events/issues/43#issuecomment-266310079) Status + OSI [Affiliation](https://opensource.org/affiliates/about)
1. Multiple licensing across repos (MIT, AGPL-3.0, Apache-2.0, etc.)
1. Meeting software: https://jitsi.org/ instead of https://talky.io, or other proposal, mentioned by realitygaps and cketti
1. Discuss getting 'opensourcedesign' id on Twitter (@ references GitHub and Twitter accounts, but in our case the ids are not the same)
1. ...

##### FOSDEM
1. [Schedule](https://fosdem.org/2017/schedule/track/open_source_design/) Status
1. [Dinner](https://github.com/opensourcedesign/events/issues/54) Status
1. [Group] sessions Status
      1. Our Open Source Design collective by jancborchardt 
      1. "Success Stories from our community" session expectations @evalica
            1. Discuss JOB [graphs](https://github.com/opensourcedesign/opensourcedesign.github.io/issues/70) + [Success](https://github.com/opensourcedesign/jobs/issues?q=is%3Aissue+label%3Ajob+is%3Aclosed) rate
            1. Other sources: Twitter, Google Analytics, ...
            1. [OpenHub](https://www.openhub.net/p/opensourcedesign) stats and repo claim
      1. ["Feedback"](https://github.com/opensourcedesign/jobs/issues/120) session expectations @evalica
       1. ...

**Comment by jancborchardt** [comment]
Since people have asked for a public calendar, I added the dates of the meetings as well as the FOSDEM Open Source Design room to a calendar you can subscribe to:
:calendar: https://cloud.nextcloud.com/apps/calendar/public/MIFAFLFJADIVX63I :)

(It’s our company instance so I can’t add people to collaborate unfortunately. But if you have a Nextcloud it will be possible to collaborate via federated sharing in the future. If you have any issues or want to contribute, please check out the repository at https://github.com/nextcloud/calendar ;)

**Comment by evalica** [comment]
### Open Collective Interview

URGENT: Deadline Sunday 18 Dec. 
TASK: [Review Draft](https://docs.google.com/document/d/1z-Np2oxogj5xUpzsQd6sRsqfsX0ijw6fHts9H71C0f0/edit)

Aseem Sood managed to take all our brainstorming notes and create a Draft.  So if anyone wants to review it and make comments, feel free to.

The publishing is targeted towards Monday, 19 Dec.

P.S: I've used this issue to announce this since this is the only issue we've talked about this interview, but in the future we should create dedicated issues for such topics.

P.P.S: @jancborchardt I have some comments in there that I would like you to give your opinion on. Ty.

**Comment by belenbarrospena** [comment]
Looks good to me :)

**Comment by jancborchardt** [comment]
And the article is now up, thanks to Open Collective!
Please retweet https://twitter.com/AseemSood_/status/810935321420595200 everyone :bird: :tada: :)

**Comment by simonv3** [comment]
## Meeting 3 (January 10th 2017) - Notes

Participants: Andreas, jancborchardt, Jan Dittrich, Felix/eppfel, evalica, Simon

Summary (feel free to edit and add): 
* We use »Open Source Design« as name and »opensourcedesign« as usernames everywhere. Twitter limits the length of a username to x amount of characters, which is why we have @opensrcdesign on there. Rarely do we use »OSD« when titles are cut short, preferable is always the full readable name.
* @eppfel (Felix) will take initiative on talking about success stories based on the jobs board [on his pad](https://pad.epp.cloud/s/BJu1siGIg) (feel free to join in).
* Possibly reach out to Open Design folks about using the openhub username: https://www.openhub.net/p/opensourcedesign
* It's fine to use multiple license across multiple repos. Preferred are AGPLv3+ and MIT.
* We'll try using jitsi next month: https://meet.jit.si/opensourcedesign
* _We're going to join the [OSI as affiliate](https://opensource.org/affiliates/about)_. Also see [logo discussion](https://github.com/opensourcedesign/events/issues/43#issuecomment-268285534) @jancborchardt will take next steps. FWIW: I'm (Simon) willing to sit in on a committee with them so you can add me as well.  

Next Meeting: February 14th

Proposed Agenda: FOSDEM wrap up, OSI initiative

**Comment by jancborchardt** [comment]
And by the way, everyone who is at FOSDEM, feel free to send me your mobile phone number (via email or Twitter dm) so I can add you to our Open Source Design @ FOSDEM group on [Signal](https://whispersystems.org/). :)

**Comment by gillisig** [comment]
@eppfel here is another potential success story from when I was hired by the guys at 5apps to redesign their widget: https://github.com/remotestorage/remotestorage.js/issues/795

**Comment by simonv3** [comment]
Bump for awareness that we have a meeting on Tuesday!

**Comment by jancborchardt** [comment]
Remember we have the call today! :)

I'll likely miss it though cause I am at a Nextcloud meetup :/

**Comment by elioqoshi** [comment]
I will try to be there, the time today should work out for me!

**Comment by simonv3** [comment]
# Meeting 4 (February 14th 2017)
Meeting: https://meet.jit.si/OpenSourceDesign
Participants: evalica, simonv3, Jan D, richlitt, Arul, Ryan Gorley, jdorfman

## Agenda: 
* How was FOSDEM? What's next?
* Automated created issues for proposals, feedback for our job board entries: [jobs#139](https://github.com/opensourcedesign/jobs/issues/139)
* Design Feedback solution [organization#48](https://github.com/opensourcedesign/organization/issues/48)
* What's the [OSI](https://github.com/opensourcedesign/events/issues/43#issuecomment-268285534) joining status?
* What do we do with our [open collective](https://opencollective.com/opensourcedesign) money?
* An automated way of signing up members.

## Notes:
* FOSDEM Went well! Plans are in the works for FOSDEM 2018.
* We'll see if there's a way to automatically create issues. @RichardLitt is going to give his thoughts on this https://github.com/opensourcedesign/organization/issues/47
* opensourcedesign/taskforce sounds good!
* Want an update about the OSI status. Ping @jancborchardt and @jdorfman should talk about this
* Talk to @jdorfman at stickermule for open source design stickers!
* Create a page for "where do you donate" and which projects you should and can donate to. More actively use the funding the repo. @RichardLitt is going to give some ideas in an issue in the funding repo.
* Simon will create an issue for doing the automated joining. 


Next meeting:  7 March 2017, 19:00 PM Berlin time

**Comment by evalica** [comment]
# Meeting 5 (March 7th 2017)
Meeting: https://meet.jit.si/OpenSourceDesign
Participants: jcb, jan dittrich, belen, elio, charlie, bernard, evalica

## Agenda: 
* [Open Source Design Summit](https://github.com/opensourcedesign/organization/labels/summit)
* Logo and OSI [affiliation](https://github.com/opensourcedesign/organization/issues/53): [elio's ideas](https://matrix.org/_matrix/media/v1/download/matrix.org/KJHoolLeVxSDLjLKuFGUVrqt)

## Notes:
- The Open Source Design Summit is set to be on October 13–18 in Berlin
  - Core days on weekend, hacking afterwards https://github.com/opensourcedesign/organization/issues/66
  - @Incabell is checking for venues, plan is maybe Wikimedia on the weekend for the discussions and Mozilla on Monday-Tuesday for hacking: https://github.com/opensourcedesign/organization/issues/59
- We need to change our logo because of trademark reasons, see the detailed comment by OSI’s @massonpj https://github.com/opensourcedesign/events/issues/43#issuecomment-283807989 – pragmatic solution could be to just go for a square instead of a circle for example
- We’re applying to become an OSI affiliate and FSFE associate https://github.com/opensourcedesign/organization/issues/53 – @jancborchardt is on it
- We want to do partnerships with other initiatives like http://openusability.org (@jdittrich talked to @guiguru) https://github.com/opensourcedesign/organization/issues/67
- We will have a local meetup in Berlin! https://github.com/opensourcedesign/events/issues/69

**Comment by jancborchardt** [comment]
Just as info regarding @elioqoshi’s points in the link:

> Become an OSI affiliate. Advantages: We can keep our current logo and are collaborating more with OSI

This has nothing to do with each other. Becoming an affiliate will change nothing about the necessity to change our logo. About the affiliate application, see https://github.com/opensourcedesign/organization/issues/53
I still think that OSI should open-source their logo and give it to the community. But just ignoring is not fair, especially since as designers we have to respect the existing legal aspects too.

(Also, please let’s keep discussions on here and not in some linked documents which might expire or vanish. ;)

**Comment by elioqoshi** [comment]
Ah, I got that wrong then.

Patrick Masson's last point made sense though so we have to weight our options. Changing our logo to a square instead of a circle would be fine for me. Let's discuss that in the call, Patrick said he would join as well.

**Comment by evalica** [comment]
# Meeting 6 (April 4th 2017)
Meeting: https://meet.jit.si/OpenSourceDesign

Meeting not held.

**Comment by jancborchardt** [comment]
Added the summary of our call at https://github.com/opensourcedesign/events/issues/49#issuecomment-283646202 ! :) Thanks everyone for attending

**Comment by massonpj** [comment]
Sorry @jancborchardt, clicked over here from [https://github.com/opensourcedesign/organization/issues/53#issuecomment-283941905]( https://github.com/opensourcedesign/organization/issues/53#issuecomment-283941905) but not sure where the notes are that you're referring too.

**Comment by elioqoshi** [comment]
@massonpj They are at https://github.com/opensourcedesign/events/issues/49#issuecomment-283646202 :)

**Comment by massonpj** [comment]
@elioqoshi I found a few comments and responded here: [https://github.com/opensourcedesign/organization/issues/53#issuecomment-285145655](https://github.com/opensourcedesign/organization/issues/53#issuecomment-285145655)

Is where you are referring?

**Comment by elioqoshi** [comment]
Yes, that works, thanks so much! Will move over there

**Comment by massonpj** [comment]
BTW, it's not just you all that I am a jerk with... https://github.com/fossjobs/fossjobs/issues/12

**Comment by simonv3** [comment]
Calendar of future events is here: 

https://cloud.nextcloud.com/apps/calendar/public/MIFAFLFJADIVX63I

Thanks to @jancborchardt 

(cc @grahamperrin)

**Comment by grahamperrin** [comment]
Edited https://github.com/opensourcedesign/events/issues/49#issuecomment-283646202 above to refer to https://github.com/opensourcedesign/organization/issues/53 where a link to 53 was broken.

**Comment by eppfel** [comment]
# Meeting 7 (May ~~2nd~~ 3rd 2017)
Meeting: https://meet.jit.si/OpenSourceDesign

Postponed for ~~40 min (19:40 CET)~~ a day (03.May 19:00 CET), because of a flat tire... 🚲 

### Agenda
- OSD Summit Venue?
   - Can @Incabell (or someone from Wikimedia) update on using Wikimedia on the weekend https://etherpad.wikimedia.org/p/opensourcedesign-summit
  - Can @elioqoshi update on using Mozilla on Monday-Tuesday?
- OSD Summit Organization
  - What has to be done?
  - Who will help?
- Updates on FSFE and OSI opensourcedesign/organization#53 opensourcedesign/organization#88
   - @jancborchardt to update on this
- Update on partnership with OpenUsability opensourcedesign/organization#67
   - Can @jdittrich give an update on this? 
- The Discourse
   - Increasing Discourse use
   - What to do in the open? And what not?
- S.W.A.G.
  - Should we print stickers with the square logo and text?
- @jancborchardt update on CSSConf Berlin

**Comment by ei8fdb** [comment]
(If I've missed something, or got something wrong: feel free to correct it!)

### Notes from 3 May 2017 meeting
In attendance today: @jancborchardt @jdittrich @simonv3 @ei8fdb @grahamperrin @evalica @belenbarrospena @ryangorley @eppfel 
In attendance yesterday: @belenbarrospena @ei8fdb @eppfel @RichardLitt 

## OSD Summit Venue?
   - We have an almost confirmation that we can use Wikimedia location for the weekend days, and Mozilla for Monday-Tuesday days of the summit. We are still waiting for full confirmation.

## OSD Summit Organisation
  - we need a landing page for the summit - e.g. osd.net/summit and link it from events. @simonv3 is happy to take that on
  - @Incabell is following up on possibilities of funding (travel etc) for the summit
  - We need to be aware of the limits of space. This will impact on if we can sell tickets, etc.

## Using Discourse
   - We all agreed we need to start using it more. Discuss the methods we use in our projects, useful resources, etc.
  - @jdittrich mentioned he's spread it into the Wikimedia, Mozilla communities. It was suggested we all advertise it more to open source communities via different channels. In terms of who we want to "attract" its about connecting different groups of people.
  - The intent is to keep it open, developers, designers, interaction designers, logo designers, industrial designers, to the level of "users of open source design software - GIMP, Inkscape".

## Updates on FSFE and OSI
(opensourcedesign/organization#53 opensourcedesign/organization#88)
   - @jancborchardt updated the FSFE application is going well. It's expected we will be accepted. We don't have a date yet. The application for OSI has not been submitted yet.
- We also identified we need to do work on sources of funding. If people have suggestions, [open an issue](https://github.com/opensourcedesign/events/issues/new).

## Update on partnership with OpenUsability 
(opensourcedesign/organization#67)
  - If we have a clear proposal "we" think that they'll be happy and maybe engage a bit more.
  - We're not sure if its a blocker for them that if we have a different focus. This might be a difficulty for them. @jancborchardt / @jdittrich are going to discuss with them in person. Maybe we can then have some discussion on Discourse with them.

## OSD at CSSConf Berlin
  - @jancborchardt was invited to present
  - We need to make the jump from FOSS focused conferences to more "mainstream" design conferences. Good luck Jan 😸 ✨ 

## Should we print stickers with the square logo and text?
   - We agreed to print our "square logo" stickers and maybe at, if necessary, at later stage print different stickers if we change logos

## Other news
  - @simonv3 will be in Europe. 🕺 
  - @jancborchardt mentioned the Open Tech Summit in Berlin. The call for submissions is still open (until the 10th May) - http://opentechsummit.net/

**Comment by simonv3** [comment]
Awesome, thanks for taking notes @ei8fdb!

**Comment by Xaviju** [comment]
Thanks for the notes! Btw @simonv3 if you need a hand with the development of the landing page let me know. I'll be happy to help coding. :)

**Comment by simonv3** [comment]
@Xaviju that'd be great! I just created a branch for the page. 

https://github.com/opensourcedesign/opensourcedesign.github.io/tree/summit

I don't really have any super big plans at the moment, happy to just let it grow as the summit evolves and becomes more firm.

**Comment by jancborchardt** [comment]
The notes from the last meeting are at:
https://discourse.opensourcedesign.net/t/setting-up-an-official-non-profit-organization/247

It was just Moritz and me talking about non-profit organization structures. :)

**Comment by tessgadwa** [comment]
Has a time / date been set for the next call?  I remember seeing August 1
floating around somewhere.

Tess G.

artmeetscode.org

**Comment by simonv3** [comment]
Here's the listing for the next meeting: http://opensourcedesign.net/events/open-source-design-monthly-online-meeting/

Sadly I won't be near the internet. I feel like I've been missing a lot of these recently :(

**Comment by tessgadwa** [comment]
Thanks for the info!  Sorry to miss you,  Simon.

On Jul 25, 2017 11:56 AM, "Simon" <notifications@github.com> wrote:

Here's the listing for the next meeting: http://opensourcedesign.net/
events/open-source-design-monthly-online-meeting/

Sadly I won't be near the internet. I feel like I've been missing a lot of
these recently :(

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/opensourcedesign/events/issues/49#issuecomment-317837124>,
or mute the thread

**Comment by jancborchardt** [comment]
As a reminder, the next call is today! :)

And since we move to the forum more and more, I opened a thread about it at https://discourse.opensourcedesign.net/t/monthly-open-source-design-call/253 which we can use just like we did this one.

**Comment by victoria-bondarchuk** [comment]
Would be great to have a call for FOSDEM preparation.  @jancborchardt  what do you think? 

# Meeting  (December 12 2017)
Meeting: https://meet.jit.si/OpenSourceDesign

### Agenda
 - FOSDEM TALKS
   - Discuss/decide on the final sessions 
   - Who can help in the devroom: twitting, helping at the door, etc
- FOSDEM BOTH
   -Shall we have a schedule? 
- FOSDEM DINNER
  - Who can help organizing it

**Comment by dimitrieh** [comment]
@jancborchardt Is there a public (google) calendar I can follow/import into my own calendar for open source design events and the monthly calls?

**Comment by simonv3** [comment]
@dimitrieh jan links to it earlier in the thread: https://github.com/opensourcedesign/events/issues/49#issuecomment-267208684

Edit: I've made the link in the first post a bit more explicit.

**Comment by evalica** [comment]
There is a public calendar, but apparently the meetings have been put on hold. Would be great the revitalize them, as Victoria suggested, especially since we need to organize FOSDEM.

**Comment by evalica** [comment]
@victoria-bondarchuk what time?

**Comment by victoria-bondarchuk** [comment]
Shall we do it the same time at 7pm CET? @evalica

**Comment by victoria-bondarchuk** [comment]
one more possible topic to discuss is how to make vote process more secure and if there any open tool we could use for that purpose in the future?

**Comment by dimitrieh** [comment]
thanks @simonv3 ! although i checked that link out before and now and can't find any content within that calendar :s

**Comment by simonv3** [comment]
It's very possible that @jancborchardt didn't create events this far in advance :P

**Comment by dimitrieh** [comment]
@simonv3 ahh.. as I was mainly in for it for future events :) like recurring event reminders for monthly calls and have events upcoming 3 months always up to date (perhaps update it at the start of each months meeting)

**Comment by jancborchardt** [comment]
Yep, that’s exactly it. :) I added things in the calendar up until the Summit. Added the call for Tuesday (basically today) at our usual time of 19:00 CEST (Berlin time).

We need to find a better way to do this, maybe by having a calendar widget like https://fullcalendar.io on our event page which simply shows all events from the list – and we add every call as event too. :)

**Comment by dimitrieh** [comment]
Perhaps feature this ics link on the website as well :) easy to find! single source of truth

**Comment by belenbarrospena** [comment]
Yikes, completely forgot about the call yesterday :( I hope it went well.

**Comment by victoria-bondarchuk** [comment]
@belenbarrospena we discussed voting and acceptance process. We've scheduled one more for 9th of January, maybe it could be a good opportunity to discuss in more details Both preparation and other practicalities for FOSDEM

**Comment by davelab6** [comment]
When is the next one? :)

**Comment by belenbarrospena** [comment]
Excellent question! :) I think we are all still recovering from FOSDEM. 

Maybe we could have one the first Tuesday of April (3rd)?

**Comment by victoria-bondarchuk** [comment]
+1 for 3 of April!

**Comment by davelab6** [comment]
April 3rd is fine for me

**Comment by elioqoshi** [comment]
Did the 3rd April call happen? If not, can we try another date this month? Maybe 24th April?

**Comment by simonv3** [comment]
Either the 24th of the 2nd of May works for me.

**Comment by davelab6** [comment]
If any calls happened, I missed them 😭 

When's the next one? ;)

**Comment by jancborchardt** [comment]
@davelab6 we are having a poll on the regular call date, see https://discourse.opensourcedesign.net/t/monthly-open-source-design-call/253/15 :)

**Comment by jancborchardt** [comment]
Alright, in an effort to reduce confusion, we’re closing this last issue in the events repository too. :)

I moved all the call notes from this thread to the forum at https://discourse.opensourcedesign.net/c/meta/monthly-call

Info on the call, as usual, at http://opensourcedesign.net/events/open-source-design-monthly-online-meeting/ :)

:tada:
