### ISSUE TITLE
Google Code-In 2017 Participation

### ISSUE THREAD

**Issue by evalica** [opensourcedesign/events#51]
Following a recent discussion with @jancborchardt  (see https://twitter.com/jancborchardt/status/799971698191794177) and also a query on IRC (I don't remember from whom), there was the idea to see if we want to participate in Google Code-In.

> Pre-university students ages 13 to 17 are invited to take part in Google Code-in, our global, online contest introducing teenagers to the world of open source. With a wide variety of bite-sized tasks, it’s easy for beginners to jump in and get started no matter what skills they have. Mentors from our participating organizations lend a helping hand as participants learn what it’s like to work on an open source project.

See timeline: https://developers.google.com/open-source/gci/timeline

This issue's purpose is to see if we are interested, brainstorm tasks, see if we are eligible, etc.

**Comment by mestaritonttu** [comment]
I think you could still join as co-mentors to this year's GCI. Simply look at the organizations participating and contact mentors in the ones that seem relevant to you. If they let you in, you just start creating tasks. I have once co-mentored in this way without being in an organization from the start.

**Comment by davelab6** [comment]
I think this issue should be closed :)
