### ISSUE TITLE
Some house cleaning

### ISSUE THREAD

**Issue by ei8fdb** [opensourcedesign/events#56]
Hiho all,

I've had some time on my hands so I've done some house cleaning.

I've reviewed and closed the following:

#35 (OSD Meetup - Berlin Early May 2016)
#27 (Libre Graphics Meeting 2016)
#21 (IxDA 2016 - Helsinki)
#13 (Render "Past Events" differently than Upcoming or Current Events) I updated it with with a screenshot of the events page as now
#11 (Make gh-pages default, move remaining master content over, then delete?) Looks like its done.
#8 (I meeting summary)

If something needed to be kept open, please reopen it.

#15 (Use Jekyll metadata instead of custom defined date / time data in events) has been merged, so can be closed too, I guess...

I guess someone else needs to close this issue, soon. ;)

**Comment by bnvk** [comment]
As per #15 the files still look a bit messy still as some files have `eventDate` value which should not exist. Making the date nice to read (on the website) should be done with something like this:

```
<time datetime="{{ page.date | date_to_xmlschema }}" itemprop="datePublished">
    {{ page.date | date: "%b %-d, %Y" }}
</time>
```

Which makes an interesting challenge (about "event" related data in general), as there are usually three *date* values that are relevant:

- eventStart
- eventEnd
- eventPublished

As well as something to denote if an event has been updated / changed in the case of a venue or date start/end values are changed is:

- eventUpdated

With our use case (a page of upcoming and past OSD related events) the most crucial value in a feed based view is likely to be `eventStart` which is how we want to sort the items by on [events page](http://opensourcedesign.net/events). Additionally, the concept of "recurring events" is relevant to consider here!

This might be a bit too code / dev related for this thread, but it is relevant to start thinking about how we want the pages to look and display and thus how we should be structuring the event data in the markdown files.

**Comment by jancborchardt** [comment]
While house cleaning is made, it would be good if we can ensure that all past events are actually on our events page. I can’t see any which are missing right now. Can you recall more @ei8fdb @bnvk @belenbarrospena?

**Comment by davelab6** [comment]
I suggest closing this :)
