### ISSUE TITLE
Berlin Meetup

### ISSUE THREAD

**Issue by jdittrich** [opensourcedesign/events#57]
Hello Opensourcedesigners, 

Some of us are based in Berlin and I wonder if we want to start a little meetup there. (Originally not my idea – I think @jancborchardt and @Incabell talked about this already).

Who is in Berlin and would be interested?

**Comment by elioqoshi** [comment]
I am quite a few times per year in Berlin, would be happy to be there next time

**Comment by jancborchardt** [comment]
@bnvk, @danilapellicani & @Kriesse are in Berlin for example – we had a first [Open Source Design meetup back in early 2015](http://opensourcedesign.net/events/2015/03/15/berlin-open-source-design-meetup) (also with @gillisig attending remotely). I’m in Berlin sometimes too.

We could do a regular monthly meetup maybe even on a fixed day? That usually works well and seeing how we are already ~5 people that seems to be good.

We could alternate it with the [monthly call](http://opensourcedesign.net/events/open-source-design-monthly-online-meeting/) (do it more towards the mid/end of a month). Or do it on the same day and have the Berlin group join in the call, but that doesn’t sound too productive for either case. ;) (cc @evalica @belenbarrospena @simonv3)

What do you think?

**Comment by belenbarrospena** [comment]
@jancborchardt I think I wish I was in Berlin so I could join the fun :) Sounds like a great idea, and I don't see any harm in you joining the monthly call together. 

btw, just saw the news. I hope all of you in Berlin are ok :(

**Comment by evalica** [comment]
Meeting in person is always nice, so I'm sad that I won't be able to attend. It would be nice to accept also remote participation, but I guess it depends also on the hour/day you want to meet.

**Comment by jdittrich** [comment]
**Time/Date:** What about the 3rd Tuesday of each month?
**Note**: We could also involve the LibreOffice design people in Berlin. Anyone with contact to them?

**Comment by jdittrich** [comment]
**Time/Date:** What about the 3rd Tuesday of each month?
**Note**: We could also involve the LibreOffice design people in Berlin. Anyone with contact to them?

**Comment by Incabell** [comment]
**Time**: I would prefer a Wednesday due to a personal schedule. We could also set up a [dudle.](https://dudle.inf.tu-dresden.de/)
**Note**: I would suggest meeting in a cafe or bar of our choice for the beginning, like a Stammtisch and then see where it goes.

**Comment by bnvk** [comment]
I'm all good for this. I'd vote for Wed as well. @jdittrich when shall we do one?

**Comment by jdittrich** [comment]
25th of January? Kreuzberg?

**Comment by jancborchardt** [comment]
Btw, if we do one on February 14th or 16th (Tue or Thu) I’ll also be in Berlin. :)

**Comment by evalica** [comment]
A small reminder that our monthly meeting is on February 14th

**Comment by bnvk** [comment]
Yah, let's do the first meetup on Jan 25th, then we can do another one on
Feb 14th that co-incides with the normal monthly one. Would be nice, I
think?!

**Comment by jdittrich** [comment]
@jancborchardt ping us, let’s meet 14th/16th
@all: Anybody knowing a Berlin place with WiFi, not too crowded? Or we could ask co.up? Or just meet at Kotti and ```forEach(bars){(if bar.free== true){goIn(bar); break;}}```? (aka search for a place)

**Comment by elioqoshi** [comment]
Would you like to meet at the Mozilla Offices? I could hook you up with them?

**Comment by jdittrich** [comment]
@elioqoshi nice idea! That would be great.

**Comment by elioqoshi** [comment]
When is your next meeting? Let me try to get this going for next time

**Comment by Incabell** [comment]
Hey everyone,

now that we've all had a weekend to digest the FOSDEM I suggest we have another go at the Berlin meet-up!

When are good times for everyone? 
**My constraints are: not Tuesdays, not Thursdays**

Otherwise I'm open for any day.

Cheers
Charlie

**Comment by jancborchardt** [comment]
I'll be in Berlin from February 20th – March 3rd, so could join any meetup happening then.

Am also happy for just coworking. :)

**Comment by elioqoshi** [comment]
Just ping me if you want me to talk to the Mozilla Office to offer you some space :)

**Comment by jancborchardt** [comment]
Closing in favor of the Berlin meetup announcement issue :) https://github.com/opensourcedesign/events/issues/69
