### ISSUE TITLE
OSD Workshop #1 in Tirana, Albania

### ISSUE THREAD

**Issue by elioqoshi** [opensourcedesign/events#58]
I'm happy to co-host the first OSD Workshop in our local Open Labs Hackerspace in Tirana, Albania:
https://openlabs.cc/sq/open-source-design-workshop-1/

Together with Anxhelo Lushka, a fellow design contributor to LibreOffice and Fedora, we will show the basics of GIMP and Inkscape so people can find their way around basics in Graphic Design, breaking the stereotypes that they need Adobe software for that.

When: 25 January 2017, 5:00 PM
Where: Open Labs Hackerspace, Tirana, Albania

Event on our website (Albanian):
https://openlabs.cc/sq/open-source-design-workshop-1/

Facebook Event:
https://www.facebook.com/events/730516153783875/

**Comment by evalica** [comment]
Very nice. Good luck! Do you also plan to create a PR to have it listed on http://opensourcedesign.net/events/ ?

**Comment by elioqoshi** [comment]
@evalica Just did it here:
https://github.com/opensourcedesign/events/blob/gh-pages/_posts/2017-01-25-osd-workshop-1-tirana-albania

Not sure if I did that right, first time I created an event :)

**Comment by evalica** [comment]
@elioqoshi well there is something wrong since the event is not displayed on http://opensourcedesign.net/events/ 

My first guess would be the missing extension. All the posts have ".markdown" for example "2017-01-25-osd-workshop-1-tirana-albania" should be "2017-01-25-osd-workshop-1-tirana-albania.markdown" can you try fixing that?

**Comment by jancborchardt** [comment]
Fixed the extension directly via Github web interface, now shows up at http://opensourcedesign.net/events/ :)

**Comment by elioqoshi** [comment]
Thanks @jancborchardt !
