### ISSUE TITLE
FOSDEM 2017 Group Pictures

### ISSUE THREAD

**Issue by raghunayyar** [opensourcedesign/events#63]
![dsc_1709](https://cloud.githubusercontent.com/assets/992488/22646535/2fc1b134-ec6d-11e6-88d0-ded86ff3902d.JPG)
![dsc_1710](https://cloud.githubusercontent.com/assets/992488/22646536/2fc1cda4-ec6d-11e6-9c7b-4569c8a65d73.JPG)
![dsc_1711](https://cloud.githubusercontent.com/assets/992488/22646537/2fc3f3c2-ec6d-11e6-9eca-d18fd010d324.JPG)

@opensourcedesign/people here we go boys and girls.

**Comment by raghunayyar** [comment]
If you guys took pictures, attach them here.

**Comment by bnvk** [comment]
There is about 200% more people in this picture than last year. Awesome :)
So sad to have missed it this year!

**Comment by objectadjective** [comment]
These are fantastic. Really hoping I can make it out next year!

...........................

Jeremy Anderson

Github: https://github.com/objectadjective
Twitter: https://twitter.com/ObjectAdjective
LinkedIn: http://www.linkedin.com/in/objectadjective

**Comment by evalica** [comment]
Very nice picture. We shoul add it as Twitter banner

**Comment by ei8fdb** [comment]
I can hear the words "PIXEL FUSKERS"!!

Thanks @raghunayyar you've given me my newest phrase. I'll be using it in work. :)

**Comment by belenbarrospena** [comment]
Cool photos! Boy: I had so much fun this year :)

**Comment by elioqoshi** [comment]
Love it! Great job folks!

**Comment by jancborchardt** [comment]
Opened a pull request to add the picture to the repository: https://github.com/opensourcedesign/opensourcedesign.github.io/pull/122 – please review. :)

Used the first one since it’s the best, we used it already, and it has everyone on there.

Closing hence :)
