### ISSUE TITLE
My FOSDEM 2017 notes - the good, the awesome, and the excellent!

### ISSUE THREAD

**Issue by ei8fdb** [opensourcedesign/events#65]
I was making some notes over the weekend a

## Providing sound for speakers
Leonié Watson needed to have sound for her screen reader. I think we should ask speakers if they need sound, for example for a11y related talks. If any say yes, we bring speakers for them. 
Alternatively, we bring a set of speakers just in case. 

I'd prefer we ask speakers if they need audio. Thoughts?

## Powar strip!
We had a few times where we needed to power our machines and there wasn't enough power provided in the room. 

Maybe we can ask FOSDEM organisers?

Alternatively we (1/2 people) should bring a power strip.  Thoughts?

## OSD related sessions
It would be better to have the OSD collective introduction session at the beginning of the day. Logically it makes more sense, and it also saves speakers from the terrible faith of an empty audience.

The introduction and the group photo would be better placed to be at the start of the day - this is OSD, what we do, who we are, OpenCollective, group photo, etc.

We could use the first half hour/hour of the day to have a short meeting at the beginning to discuss topics face to face.

The success stories talk would be better placed somewhere in the middle of the day, as we had it. People see the tangible impact we can have. If they're interested, they'll come join.

Thoughts?

## Twitter 
I found it helpful to have a bunch of template tweets ready to copy and paste to have scheduled with tweetdeck - tweeting talk descriptions and time slots, the link of the stream, room number etc...it saved a lot of work. I think we should add it into the #64 thread. I'll put together a list of templates I used.
 
## Room location
I had 2 people mention how the room AW121 was inaccessible to people with wheelchairs, or who have access needs. [1] 

I did apologise to both saying we didn't know the room location until we arrived on the morning. Saying that, *if* we are accepted in 2018, we should ask the FOSDEM organisers for an accessible room. 

I know there are many people with access needs who are attending the conference, and therefore all devrooms should be accessible by everyone, but it is a bit....ironic if the room with accessibility talks is inaccessible to everyone. We should try and make this better.

## Design clinic stand
I had some chats with different people about the design clinic stand over the weekend. To me having a design clinic stand doesn't make sense, like project stands. A stand is for continuous footfall, people moving by. 

We are looking for somewhere where people can sit for a period of time, and work collaboratively on something. A stand isn't suited. 

We could try and organise ourselves for a few hours on some tables in the cafeteria, maybe put up a notice "Open Source Design clinic...", etc. Or advertise it and "give people appointments"...

I wonder if we'd need to get agreement from the organisers? Alternatively we could not advertise it, and just sit there, like the VLC guys did. It looked like they were using it as a meeting/hacking/meet-up area. 

Thoughts?

## Panel
I thought the way the interactive panel ran was excellent. I'd love to see the same/similar process (question, discussion, voting, discussion) happening again. 

Maybe a little longer, 30-40 mins. Thoughts?
 
I'd like to hear others thoughts...

[1] https://twitter.com/_Phelan_/status/828191877325320192

**Comment by belenbarrospena** [comment]
Somehow relevant to this issue: I believe feedback to the FOSDEM organisers can be sent to feedback@fosdem.org

**Comment by jdittrich** [comment]
**Power**: Yes, general lack of sockets

**Accessibility**: Agree, in that regard, the room was terrible.

**Design clinic:** Could be fun, I would be open to volunteer there.

**Comment by jancborchardt** [comment]
> I'd prefer we ask speakers if they need audio. Thoughts?

Yup, agree.

> Alternatively we (1/2 people) should bring a power strip. Thoughts?

Yeah, or we ask FOSDEM organizers. In general then we should place the power strips in the middle of the rows or far away from the door so we make sure those people sitting with their laptops don’t block entrance for additional folks coming in. :)


> We could use the first half hour/hour of the day to have a short meeting at the beginning to discuss topics face to face.

This is a great call actually, yes. That way we can properly fill up the beginning and make sure the main people active in Open Source Design (and those who want to get involved more) are present. cc @evalica @victoria-bondarchuk @elioqoshi @bnvk what do you think?

> The success stories talk would be better placed somewhere in the middle of the day, as we had it. People see the tangible impact we can have. If they're interested, they'll come join.

Yup, and that way we have another point where we directly mention Open Source Design. We can do the group photo either at the start of the day or in the middle there.


> if we are accepted in 2018, we should ask the FOSDEM organisers for an accessible room.

Absolutely.

> We could try and organise ourselves for a few hours on some tables in the cafeteria, maybe put up a notice "Open Source Design clinic...", etc. Or advertise it and "give people appointments"...

Yeah, I also went around the booths and were it was relevant I advertised our Job board session. And that’s what that session is for. We can simply put up posters with:

> [our logo]
> **Need design help?**
> Post your project on
> opensourcedesign.net/jobs
> Or come to the Open Source Design room in AW1.141

Right? This possibly fosters the greater community much more than giving 1on1 design help. :) And if one of us is interested in a specific project we can still do that.


> I thought the way the interactive panel ran was excellent. I'd love to see the same/similar process (question, discussion, voting, discussion) happening again.
> Maybe a little longer, 30-40 mins. Thoughts?

Yep! I think the timing was fine though. :) It’s a strength of our track that we have short and very informative talks which don’t drag on for too long.


Another point at the end: Maybe we can print posters or small flyers / business card size with a short intro of how to get involved into Open Source Design, or what we do events-wise and with the job board. That would be useful also for other conferences, ref https://github.com/opensourcedesign/organization/issues/54

**Comment by evalica** [comment]
> We could use the first half hour/hour of the day to have a short meeting at the beginning to discuss topics face to face.

We could add more interactive sessions between talks, like brainstormings and discussions. 
Things to consider: 
- deciding what percentage we dedicate to this kind of sessions (30%?), 
- if they should be separate (maybe in the other day then the track, maybe at the booth, or just at the summit) or inside the track, 
- it depends also on the number of talks proposals we receive and how much we want to encourage new people to talk; if the proposed subjects are very interesting; etc.
- also these sessions need to be proposed and entered inside Penta, so we will need someone that is accountable for every session and dedicates time to organize it;

**Comment by davelab6** [comment]
Should this issue be closed?
