### ISSUE TITLE
FOSS North 2017 - Gothenburg 

### ISSUE THREAD

**Issue by raghunayyar** [opensourcedesign/events#66]
@andreasn I think you should join! :)

**Comment by andreasn** [comment]
http://foss-north.se/
I am actually helping organize that conference

**Comment by raghunayyar** [comment]
Nice, I will meet you there. I submitted my proposal for a talk I gave at FOSDEM.
I am glad to see some initiative up north.

**Comment by raghunayyar** [comment]
Also, since I live in Stockholm and the website is extremely unclear about the organisers part, let me know if you need my help.

**Comment by raghunayyar** [comment]
Just confirmed that I am speaking at FOSS North, would be talking about Open Source Design. ^_^

**Comment by evalica** [comment]
@raghunayyar wdyt about having a PR to list the event on http://opensourcedesign.net/events/ ?

**Comment by raghunayyar** [comment]
@evalica done, here you go : https://github.com/opensourcedesign/events/pull/70

**Comment by jancborchardt** [comment]
@raghunayyar @andreasn can you write a quick article about the open source design stuff you did at the event? :) We can then publish it in our articles section. :)

Also, you should start a local meetup wherever you are in Sweden. :) Open a thread at https://discourse.opensourcedesign.net/c/meetups
