### ISSUE TITLE
Open Source Design meetup at IFF

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/events#67]
Heya, so I’ll be at [Internet Freedom Festival in Valencia](https://internetfreedomfestival.org/) next week. Anyone else of you?

cc @belenbarrospena @ei8fdb @Xaviju @ameellio, or do you know anyone who will be there @victoria-bondarchuk @bnvk @evalica @simonv3 @eppfel?

We could organize a self-organized session as a meetup maybe? https://internetfreedomfestival.org/wiki/index.php/Self-Organized_Schedule

**Comment by belenbarrospena** [comment]
@ei8fdb and I are going. See you there!

**Comment by ei8fdb** [comment]
@jancborchardt Baaah you should have told me before. Very glad to see that! We could have submitted a session!

Last year I was one of the design track curators with @ameellio. I submitted an "Intro to Open Source Design" session with @bnvk but no-one understood who we were! :P

Me and @belenbarrospena are doing some sessions there.

It is a good conference to get an intro to a niche area of an open source supporting community. Let's try and organise our message to the other IFFers. :)

**Comment by ei8fdb** [comment]
PS: yes lets organise a self-organised session. @belenbarrospena is there from Sunday-Tuesday and me til Wednesday.

**Comment by Xaviju** [comment]
Oh I didn't know you were coming!! I'll be in Madrid 😢
Valencia its my hometown but sadly I am missing the event because we have a Taiga release next week.
Enjoy!

**Comment by belenbarrospena** [comment]
totally off topic, but bear with me. @xaviju where is the best paella in
town? It's very hard to find the good places! :D

**Comment by danicatalan** [comment]
I will be there too!

@xaviju che, you are going to miss a good one :(

**Comment by Xaviju** [comment]
@belenbarrospena my grandmother's paella is the best, no question. 😄 

-------

If you have a car or enough time (bus) I recommend you [this place (out of town)](https://www.tripadvisor.com/Restaurant_Review-g187529-d3155486-Reviews-El_Redoli-Valencia_Province_of_Valencia_Valencian_Country.html)

If you'll stay in the city, I usually [go here](https://www.tripadvisor.com/Restaurant_Review-g187529-d1504743-Reviews-Restaurante_Llevant-Valencia_Province_of_Valencia_Valencian_Country.html)

Close to the event there is [one very known](https://www.tripadvisor.com/Restaurant_Review-g187529-d987414-Reviews-La_Pepica-Valencia_Province_of_Valencia_Valencian_Country.html) (but very touristy) the Hemigway favourite when he was there 

Please ask me anything offtopic about the city. I'll try to help: xavi at gmail dot com

**Comment by belenbarrospena** [comment]
Gracias @xaviju :) We will all drop by your grandmother's on Sunday :b

**Comment by ei8fdb** [comment]
@Xaviju Campeón! Gracias :)

So @danicatalan @belenbarrospena @jancborchardt and@anyoneelsegoingtoIFF2017 I feel an impromptu OSD meetup happening at a paella restaurant? :)

**Comment by danicatalan** [comment]
Any grandmother's paella is the best :)

For me the best place is Descubre L'Horta, great paella and awesome local experience: https://www.tripadvisor.es/Attraction_Review-g187529-d3975725-Reviews-Descubre_L_Horta-Valencia_Province_of_Valencia_Valencian_Country.html

**Comment by danicatalan** [comment]
@ei8fdb or maybe a OSD meetup happening in a Mascletà :)

**Comment by saoun** [comment]
Heya,
I'm one of the fellows for the Communications & Design track at IFF. Hit me up if you have any questions!

**Comment by jancborchardt** [comment]
@saoun cool, I shot you a tweet, let’s meet tomorrow maybe? cc @danicatalan you around too?

Unfortunately @belenbarrospena and @ei8fdb couldn’t make it to IFF after all :(

**Comment by Xaviju** [comment]
Is this finished, how it was? Please share some posts or comments summarizing the event for those of us who missed it.

@jancborchardt should we close this?

**Comment by jancborchardt** [comment]
Yeah, it was a cool event! We had some design helpdesks with @ameellio @toberndo @teller @eff-soraya @gusandrews and more :)
https://twitter.com/ameellio/status/839834263637864448
https://twitter.com/jancborchardt/status/839487062755717121
