### ISSUE TITLE
Open Source Design Madrid meetup

### ISSUE THREAD

**Issue by Xaviju** [opensourcedesign/events#76]
Hello world!

## We created the Open Source Design meetup in Madrid!
`<excitement>`Yay!!`</excitement>`

Our plans are to meet on **Wednesday 31rst May at 19:30**. There is a meetup page to join the event: [https://www.meetup.com/es-ES/Open-Source-Design-Madrid-Chapter/](https://www.meetup.com/es-ES/Open-Source-Design-Madrid-Chapter/ )
 
We are still looking looking for an awesome location for our first meetup. If you have any idea on where can we meet, please let us know. 

**Are you in Madrid? [Join us](https://www.meetup.com/es-ES/Open-Source-Design-Madrid-Chapter/events/240037659/)!!**

@victoria-bondarchuk @myfunnyandy @elhombretecla @m1guelpf @victoria-bondarchuk

**Comment by evalica** [comment]
Victoria goes 2 times :) Have fun!

**Comment by jancborchardt** [comment]
Great stuff! :) Have fun and let us know what you talked about or worked on! :)

**Comment by bzz** [comment]
It's been great event, thank everyone who showed up and kudos @victoria-bondarchuk and  @Xaviju for effort kick-starting it Madrid!

Few things that we discussed below.

--------------

### What can we do together?
 - bring more designers
 - bring more projects
 - teach about open source 


### Open questions rose though the discussion:
 - how to recruit more designers? More then half of the people were on the engineering/business side.
 - how design process works in your organization?
 - open surce project that need designers?
 - teach opensource? (git? sketch analog+github?)
 - bring some projects that we like, that we could work on (all stages) as a group
 - is there list of local opensource projects that might need help? OSWeekend
 - build a reference: list of open-source alternatives for designer tools?? 
    (Xavi: alt tools for illustrations and animation, tutorials and workflows)
 - existing groups in Mardid: ladies UX, UXacademy, interaction design foundation
 - a page: why a designer want to contribute or be using to OSS?
 - are there a successful "cases" of UX? as a way to introduce ppl. Example of companies (@jancborchardt knows )
 
This is by no means a complete list, please, chime in an add what you think is missing.

And let's decide together what shall we do for our next event! Can discuss here, or on [OSD discourse](https://discourse.opensourcedesign.net/t/madrid-spain/164/2)

**Comment by m1guelpf** [comment]
I hope to be able go to the next one!

**Comment by jancborchardt** [comment]
@bzz @m1guelpf let’s guide the discussion to our Discourse into the local Madrid meetup thread: https://discourse.opensourcedesign.net/t/madrid-spain/164 :)

@bzz can you post the results there too and then close this thread? We should keep all the info in one place, and we should push our forum for discussion, since we use Github for working on specific parts of the website. :)

**Comment by evalica** [comment]
can we close this event?

**Comment by Xaviju** [comment]
Yes

**Comment by jancborchardt** [comment]
@xaviju can you add the past event to our events list at https://github.com/opensourcedesign/events/tree/gh-pages/_posts :) Simply copypaste a post and change the details. It would be great if we could have all events there so people see we have a lot of activity. ;)

**Comment by Xaviju** [comment]
@jancborchardt PR done :) https://github.com/opensourcedesign/events/pull/81
