### ISSUE TITLE
I meeting summary

### ISSUE THREAD

**Issue by Xaviju** [opensourcedesign/events#8]
I really wanted to attend the planning meeting yesterday on video chat but it was impossible. I would like to know the future plans and how to contribute to the community.
There will be a meeting summary?

Thanks!

**Comment by simonv3** [comment]
:+1: There should be, if it ended up happening. @Xaviju, a lot of the conversation happens in IRC. Have you had a look there? (We're still trying to figure out a way to make that a bit more accessible, but for now, you can access it through [the freenode webchat](https://webchat.freenode.net/?channels=opensourcedesign)).

You can also see the logs of the channel [on botbot](https://botbot.me/freenode/opensourcedesign/). The fact that there's no talk of a meeting there makes me think that it didn't happen!

**Comment by Xaviju** [comment]
Thanks @simonv3 i didn't have a look at the IRC channel (there is a lot of info here and there and its hard to summarize it all for newcomers) but I will.

Thanks for the links!

**Comment by simonv3** [comment]
I totally agree with the scattered info. 

@bnvk @jancborchardt Maybe we could turn the first meeting notes into a website, and publish that website?

I'll probably have some time this weekend to work on the job board as well.

**Comment by Xaviju** [comment]
I can help with a notes website (something like a release notes website made with a simple static site generator?). Probably something like this should be linked to a more relevant website, not sure if there is any plan already.

In both cases, I'll be happy to help :smile:

**Comment by simonv3** [comment]
I think that's exactly the plan. If you submit a PR for this repo I'm sure we'll accept it!

**Comment by Xaviju** [comment]
What do you think about using [pelican](http://docs.getpelican.com/en/3.5.0/) to create a static notes site that regenerates every update (on commit hook) and publish automatically to github pages?
Example: [my blog code](https://github.com/Xaviju/blog)
Any other idea? Preferred static site generator?

**Comment by bnvk** [comment]
@Xaviju heya yes your helping generating a static site would be greatly appreciated. As was being said IRC, we're using Jeykll, which I think is pretty similar to Pelican. My ultimate goal is to have the root site `opensourcedesign.github.io` and the smaller sub repos like `/events` all share a similar style of navbar and such, but I haven't figured out the exact best way to do this... we could go pull JS and load a navbar via AJAX calls, but I wonder if there is another way.

Anywho, more chats in IRC, and feel free to take a stab at this :)

**Comment by Xaviju** [comment]
Thanks @bnvk! :+1: 
Sounds nice, are there any design guidelines so far for the site and sub repos?

**Comment by bnvk** [comment]
@Xaviju not yet, as no one has taken inniative to kick it off. We're plannong on using the icon the rad @designopen folks made as per [this thread](https://github.com/DesignOpen/designopen.github.io/issues/211) 

I sketched out rough "architecture" I was thinking for the main [opensourcedesign.net](http://opensourcedesign.net) homepage in ![this image](https://raw.githubusercontent.com/opensourcedesign/events/master/2015-03-15%20Berlin%20Open%20Source%20Design%20meetup/sketch%20of%20OSD%2BA%20concept%20by%20brennan.jpg)

Feel free to take a stab at whatever inspires you / seems sensible... we can all fork, iterate reshape or revert things, GIT FTW :smile:

**Comment by Xaviju** [comment]
Nice, this is getting a little bit off-topic here so I leave this issue open until we have a notes page with this meeting summary entry. I'll open a new issue about the site with Jekill and assign it to myself.

Thanks!

**Comment by ei8fdb** [comment]
I think this issue is definitely done? We have a website. :)

If not, please reopen it. (I'm bored and got some time to do house-cleaning....)
