### ISSUE TITLE
Create a simple event notes page

### ISSUE THREAD

**Issue by Xaviju** [opensourcedesign/events#9]
From issue https://github.com/opensourcedesign/events/issues/8

> Maybe we could turn the first meeting notes into a website, and publish that website?
> 
> I can help with a notes website (something like a release notes website made with a simple static site generator?)
> 
> As was being said IRC, we're using Jeykll, which I think is pretty similar to Pelican. My ultimate goal is to have the root site opensourcedesign.github.io and the smaller sub repos like /events all share a similar style of navbar and such (...)

So we need a simple notes static website created with Jekill (as said in previous conversations) to write notes about open source meetings and events.

**Comment by jdittrich** [comment]
+1

**Comment by bnvk** [comment]
@Xaviju sounds like a good approach for this task :)

**Comment by Xaviju** [comment]
If you know about other pages that could be a source of inspiration for this task (I'm thinking of something really clean and readable (think **Medium** but less blog-gish).
Links and ideas are welcome!

**Comment by simonv3** [comment]
^ this is why we need some sort of communal inspiration board I think that goes beyond just our resources. @Xaviju how do you feel about using pinterest (or a similar, open source, tool) for this?

**Comment by Xaviju** [comment]
I've been searching for an open source tool for this tasks, but I didn't find any of them. I suggest, if there is no open source tool available, to use **concept.ly** as an alternative of pinterest (i don't like pinterest, to be honest). 
I can share a link here so users can see the screens, navigate through them, and give feedback.

A test example from concept.ly: https://app.concept.ly/home/share.vz?uid=1429612841918

**Comment by plastelina** [comment]
here are few ideas(also depends on what exactly would you like to build and what functionality it will serve-mood board, task board, or concept board that will be used by both parties to design and comment, update, or just create inspirations...)
https://zeplin.io/
http://alternativeto.net/software/pencil-project/
https://layervault.com/
http://www.myyna.com/
http://board.cubettech.com/

and finally https://github.com/pinry/pinry

thanks!

**Comment by Xaviju** [comment]
@plastelina Nice! There are some tools I didn't know. :) 
I think the idea is a **concept board** "that will be used by both parties to design and comment, update, or just create inspirations...)"
The thing is that I am not sure if the Pinboard style is the better for this task but I am open to use them if you think its better option. I would like to use something like concept.ly or invision, but open source. 

What do you think? 
What would you prefer to use in this case?

Thanks!

**Comment by simonv3** [comment]
There's a couple of tools there that look like they're what we need (and the need has come up before https://github.com/opensourcedesign/job-board/issues/26), so maybe it makes sense to install an inspiration board tool on someone's server that people can use? 

@Xaviju I'm intrigued in how you'd use invision or conceptly for this kind of thing (just gathering ideas). Would you post each thing individually and people can use it? That's a way I hadn't thought at all of using those products, I totally think it could work.

**Comment by Xaviju** [comment]
@simonv3 I'm not sure, I was thinking more of a tool that we can use for everything. 
For gathering ideas and discussion the feature I like is the possibility of add comments in areas of the screen. I use it in my work to ask my colleagues what they think about some ideas, and then we discuss about the details in the tool. Later on, we could also discuss a mockup or design, before it gets actually coded.
Pinterest-style board is also fine, we can use @plastelina links.

I will start by gathering some nice inspiration sites together to ensure that we are all thinking about the same layout and style. Don't know if there is any other previous workflow for this. If not, I will check the links to find which one looks better and open an account to share the links with the the rest and add any examples you find. We could follow the discussion there until we have a first mockup.

What do you think?

Btw, already installed and used Jekyll, it was easy :)

**Comment by simonv3** [comment]
Hey @Xaviju, @jancborchardt just took some time to put together the main website design. It's simple and straightforward. Have a look here - http://opensourcedesign.net/, the idea being that all sub-sites should try to follow the same template, just to keep a coherent theme across the network of opensource sites. 

Obviously we're open to changes to the design as well, but thought I'd let you know!

**Comment by Xaviju** [comment]
@simonv3 great! I was thinking in something quite similar! I will follow same styles, I love its simplicity and readability. 

One last thing: If we make a PR to the main site to edit its styles or layout, and this becomes a part of the main website, same updates in the code should be done to both repos, right? To keep coherence.
That sounds like its going to be hard to keep same styles across the site, isn't it?

**Comment by simonv3** [comment]
Yeah, it’ll be a bit hard to maintain. What I’ve done for the `jobs` repo is to reference the main website styles directly in the `<head>` part, which is one less thing. Have a look at that repository to see how I did both the header file and the head file. (There’s references to the actual project name as well as the links.

What we want is the compiled version of those files, not the liquid template.

Ideally we can create a post-commit hook on the website repository that moves across the compiled header and footer files to any sub pages of the website, but that’s probably too much work at the moment. A simple copy paste from the one into the other is probably all right.

—

**Comment by Xaviju** [comment]
Maybe its a little late (I've read the site merge discussion in organization) but I commited the events page we talked about in the branch gh-pages. https://github.com/opensourcedesign/events/tree/gh-pages

**Comment by bnvk** [comment]
@Xaviju not at all late, we just got the site up 3 days ago... That is AWESOME :+1: thank you so much!

I'll add a link to the main page to it

**Comment by bnvk** [comment]
@Xaviju however, upon clicking on the title of event it goes to a 404 page. It looks like it's routing the wrong URL structure from the Jekyll data. Will investigate!

**Comment by Xaviju** [comment]
I tried to copy the work previously done in the other pages (as job listing), sorry if something is wrong. Don't hesitate to ask me to change something :+1:

**Comment by jancborchardt** [comment]
@Xaviju dude, awesome stuff! :) Getting more and more valuable sections up on the site!
