### ISSUE TITLE
LGM 2018 - Libre Graphics Meeting

### ISSUE THREAD

**Issue by valessiobrito** [opensourcedesign/events#95]
Inviting volunteers to help organize, get support, get involved with the organization or participation.

More info: http://libregraphicsmeeting.org/2018/2018-edition/

**Comment by jancborchardt** [comment]
Hey @valessiobrito! :) To have this event properly listed on http://opensourcedesign.net/events/, could you add it to the website?

For that simply go to https://github.com/opensourcedesign/events/tree/master/_posts, copy the existing LGM event from 2016, and adjust the details and name in the new file. :) Submit it as a pull request and we can review. Thanks!
